### ISSUE TITLE
Pulseaudio GUI Input and Output names not displayed correctly, causes unusual side effect.

### ISSUE THREAD

**Issue by raymundd** [arodland/nDAX#10]
I'm running AlmaLinux 8 (a free REDHAT 8.4 distro).

I'm running two instances of nDAX with different -source and -sink sound device names, e.g. "RED.rx", "RED.tx" and "BLUE.rx", "BLUE.tx" and two instances of WSJT-X which works great, however, if I run the gnome-control-center and view the Sound panel I see two instances for the Output named "Flex TX" and two for the Input named "Flex RX", should these not match the names supplied with -sink and -source?

Ordinarily this doesn't cause a problem, but one unusual side-effect of this is, if I open the gnome-control-center for the Inputs and click on either of the devices named "Flex RX" this seems to immediately override the association of nDAX and WSJT-X instances audio stream and cause the audio stream of the selected Input device to be duplicated to both WSJT-X, which is not ideal. The only fix is to stop and restart the nDAX/WSJT-X instances.

I noticed when running "pacmd list-sources" that this shows that the name used in gnome-control-center is I guess coming from the device.description parameter? Should this not be the same name as provided with the -sink and -source nDAX options?

**Comment by raymundd** [comment]
Ok, so I quickly forked your code and tried changing the device-descriptions to be a concatenation of "Flex TX - " and the user supplied sink string and also same for the source "Flex RX - ",e.g. "Flex TX - BLUE.tx" but still get the odd effect where selecting the Sound Input device in gnome-control-center over-rides the WSJT-X audio association.

I have found that one way to restore the nDAX and WSJT-X association is to go into WSJT-X and change the "soundcard" input and output to anything other than the nDAX channels, click OK and then go back and change WSJT-X soundcard to the nDAX channels source and sink.

**Comment by arodland** [comment]
See also https://github.com/kc2g-flex-tools/nDAX/issues/4

Just something I haven't gotten around to yet. Send a patch if you like, otherwise I'll get around to it soonish :)

**Comment by raymundd** [comment]
I've carried out a bit more research and it seems that the duplication of the sound to all outputs is "by design" in the gnome-control-center, always defaults to pass audio from a single selected Input device to all Output devices.... my bad :(
