### ISSUE TITLE
Warning on Real Time Thread

### ISSUE THREAD

**Issue by iz4tow** [arodland/nDAX#11]
Hi,
I launched nDAX application (last version downloaded today), it workds but in logs i see this:
```
./nDAX-linux-amd64  -tx false
12:44PM INF Waiting for station station=Flex
12:44PM WRN Couldn't get realtime error="MakeThreadRealtime: Operation not permitted" thread="udp thread"
12:44PM INF Found Client id=0x0000000 uuid=XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXXXXXXXX
12:44PM INF Looking for slice slice_id=A
12:44PM INF Found slice slice_idx=0
12:44PM INF Enabled RX DAX stream stream_id=4000008
12:44PM INF Enabled TX DAX stream stream_id=84000000
12:44PM WRN Couldn't get realtime error="MakeThreadRealtime: Operation not permitted" thread="rx thread"
12:44PM WRN Couldn't get realtime error="MakeThreadRealtime: Operation not permitted" thread="tx thread"
```

I'm using Ubuntu Desktop 20.04.05 I think the issue is related to ulimit, but I don't know how to resolve it. Can you help me? Thx

**Comment by arodland** [comment]
If everything is working okay, then you can simply ignore the messages, or run with `-rt=false` to make them go away.

If you have stuttering problems and you need realtime to fix them, then you need to figure out why rtkit is denying the requests. Either it thinks that your user shouldn't have realtime at all, or that you already have the maximum number of realtime threads it's willing to give out. That's a distro-specific configuration issue that I can't offer very much help with.
