### ISSUE TITLE
SYSTEMD issue

### ISSUE THREAD

**Issue by iz4tow** [arodland/nDAX#12]
Hi,
I'm trying to use nDAX from systemd
I'm using this string:
`/home/user/nDAX -log-level debug -rt false -tx false`

starting from user terminal it works (but it seems to ignore -rt flag and -tx flag), starting from systemd I found this error:
12:59PM FTL pulse.NewClient failed error="dial unix pulse/native: connect: no such file or directory"

Can you help me?
Thanks

**Comment by iz4tow** [comment]
I' sorry I resolved using systemctl --user.
But the flag issue remains

**Comment by arodland** [comment]
I think it needs to be `-rt=false -tx=false`. Sorry about misleading you by using the wrong syntax in a previous comment :)
