### ISSUE TITLE
distorted receive audio after transmit

### ISSUE THREAD

**Issue by rayslinky** [arodland/nDAX#13]
Frequently after TX, the RX audio will be distorted, as shown in the attached screenshot. The top is audio provided by nDAX on a host running Ubuntu 23.04.  The bottom is WSJT-X running on windows, attached to the same slice, but the windows DAX audio, where I don't see the issue. Changing bands and immediately changing back will correct the audio until I transmit a couple of times again... I changed bands/changed back in the 17:38:15 time slot, which is why the top of the waterfall looks normal.

This time, nDAX was started as `nDAX -radio flex.lan -latency 200 -packet-buffer 6`, I've tried various iterations (including the defaults) and pretty consistently run into this issue. 

Has anyone else seen this?

![Screenshot_2023-07-28_13-39-45](https://github.com/kc2g-flex-tools/nDAX/assets/7922656/670db741-43b0-492c-bf6b-b9bf812e707d)

**Comment by arodland** [comment]
Interesting. I haven't seen this.

Would you be able to provide an audio recording sample, e.g. by using  
`parec -d flexdax.rx --rate=48000 --format=s16le flex.wav`  
and see if you can induce the glitch while it's recording, and share the file?

Also, could you see if passing the `-high-bw` option to nDAX makes any difference?

**Comment by rayslinky** [comment]
I think this is actually a linux throttling issue. The problem went away after I installed/enabled `tuned` and selected the `realtime` profile.

**Comment by rayslinky** [comment]
I installed tuned and had limited relief, but eventually the artifacts came back. I have since removed pipewire and started pulseaudio instead, and have had a couple days of artifact free audio. 🤞

**Comment by arodland** [comment]
Okay. Yeah, it seems like pipewire's version of PA's `module-pipe-source` is not quite up to snuff. It also delivers higher latency than pulseaudio.

Would you be willing to do me a favor and add an issue on pipewire's GitLab issue tracker, tagging it as a regression from PulseAudio, and see if they can make anything of it? I'll join the discussion there.

**Comment by rayslinky** [comment]
opened https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3478
