### ISSUE TITLE
No sound from nDax

### ISSUE THREAD

**Issue by scap1784** [arodland/nDAX#7]
Ran nDax as follows: 

```
scap@Computer:~$ ./nDAX-linux-amd64 -station Maestro -daxch 2
2020/06/23 04:50:07 Waiting for station: Maestro
2020/06/23 04:50:07 Found client ID 0x7518157A UUID AC586976-05EE-4252-9B9F-692189960DFA
2020/06/23 04:50:07 Looking for slice: A
2020/06/23 04:50:07 Found slice 0
2020/06/23 04:50:07 enabled RX DAX stream 4000009
2020/06/23 04:50:07 enabled TX DAX stream 84000000
excessSamples: 0
```

I was able to set up wsjt-x with the flexdax.rx.monitor and flexdax.tx
TX seems to work and I even got rig control working with nCat. I was spotted as well so I know I got out. RX I have no audio though. 

I don't see any audio being sent from nDax to the RX loopback.
![image](https://user-images.githubusercontent.com/1787703/85390095-efc3a480-b50d-11ea-8b5d-0eb43232b952.png)

**Comment by arodland** [comment]
Does it work if you don't use `-daxch 2` ?

**Comment by scap1784** [comment]
no I did that to try something different. The slice was also set to channel 2. I have tried one as well.

**Comment by arodland** [comment]
Okay, I'll look into it.

**Comment by scap1784** [comment]
I am using a 6600 I think from your QRZ page your using a 6400... Don't know why that would matter as the protocols are the same. I am writing some software for this as well and I have used your code to understand various parts of the protocol. I am not as far as you. I am not very familar with Go but I will take a look this evening at the code and see if I can't figure it out... Its almost like the program just isn't sending the audio to pulse. 

Oh and as for the computer. I am running Cinnamon (4.4.8) on Linux Mint (19.3).

**Comment by arodland** [comment]
Try using `tcpdump` or `ngrep` to see whether you're getting a stream of
UDP packets from the radio. Also try running nDAX with `-debug-timing`
which will enable lots of additional debug messages. Let it run for a few
seconds, ^C it, and then provide the complete output.

**Comment by scap1784** [comment]
![Screenshot from 2020-06-23 14-49-50](https://user-images.githubusercontent.com/1787703/85452775-d730aa00-b560-11ea-9684-218d48a4f9d8.png)
Lots of UDP traffic. 

Not really any debug print out
```
scap@Jupiter:~$ ./nDAX-linux-amd64 -daxch 2 -station N5SDR-Maestro -debug-timing2020/06/23 14:48:22 Waiting for station: N5SDR-Maestro
2020/06/23 14:48:22 Found client ID 0x7518157A UUID AC586976-05EE-4252-9B9F-692189960DFA
2020/06/23 14:48:23 Looking for slice: A
2020/06/23 14:48:23 Found slice 0
2020/06/23 14:48:23 enabled RX DAX stream 4000009
2020/06/23 14:48:23 enabled TX DAX stream 84000000
excessSamples: 0
```

**Comment by scap1784** [comment]
Ok so note Linux Mint has a pretty restrictive firewall... Open it up and stuff works. Thanks for the responses and writing some useful software! :)

**Comment by scap1784** [comment]
This is awesome... I don't need windows anymore :)

**Comment by arodland** [comment]
Thanks for the info — seems like I have something to add to the documentation :)
