### ISSUE TITLE
Feature request - Manually configure the network port binding of nDAX to aid use of static firewall rules.

### ISSUE THREAD

**Issue by raymundd** [arodland/nDAX#8]
Please is it possible to provide an option to statically define the udp port that nDAX will use at runtime?

Currently nDAX binds to a random port number each time it starts which makes setting up static firewall rules impossible.

A command line option to allow the user to provide the udp port to bind to would be ideal.

Thanks.

**Comment by arodland** [comment]
Included in latest release.
